version: "3.8"

services:

  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always

  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    depends_on:
      - db
    command: make serve

  alembic:
    build: .
    env_file:
      - .env
    command: make migrate
    depends_on:
      - db

volumes:
  db:
    driver: local
